server:
  port: 8005

spring:
  application:
    name: grpc-service

grpc:
  server:
    port: 7005

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
